id: I6307E7B0
legacy_id: P000483
ocr_import_info:
  bdrc_scan_id: W23438
  source: bdrc
  ocr_info:
    timestamp: '2020-12-24T08:12:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T10:15:37.274015+00:00'
last_modified: 2022-08-27 18:15:45.497980
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23438
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23438
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་མཁྱེན་པད་དཀར་གྱི་བླ་སྒྲུབ་ཡེ་ཤེས་མཆོག་སྟེར།
statistics: null
quality: null
bases:
  I1937:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1937
      total_pages: 94
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1937.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
